import java.io.IOException;
import java.util.Scanner;
 

public class Main {
 
    public static void main(String[] args) throws IOException {
        Scanner teclado = new Scanner (System.in);
       

        int A,B,C,D,E;
      
        
        A = teclado.nextInt();
        
        B = teclado.nextInt();
        
        C = teclado.nextInt();
        
        D = (A+B+Math.abs(A-B))/2;
        
        E  = (D + C + Math.abs(D - C)) / 2;
        
        System.out.printf(E +" eh o maior\n");
    

    }
 
}
