import java.io.IOException;
import java.util.Scanner;
 

public class Main {
 
    public static void main(String[] args) throws IOException {
        Scanner teclado = new Scanner (System.in);
       
        int A,B;
        double C,salario;
        
        A = teclado.nextInt();
        B = teclado.nextInt();
        C = teclado.nextDouble();
        salario = B * C;
        
        System.out.printf("NUMBER = %d\n", A);
        System.out.printf("SALARY = U$ %.2f\n", salario);
    }
 
}
