import java.io.IOException;
import java.util.Scanner;
 

public class Main {
 
    public static void main(String[] args) throws IOException {
        Scanner teclado = new Scanner (System.in);
       

        float A,B,D,E;
        double C,F,G;
        
        A = teclado.nextFloat();
        B = teclado.nextFloat();
        C = teclado.nextDouble();
        D = teclado.nextFloat();
        E = teclado.nextFloat();
        F = teclado.nextDouble();
        G = (B*C)+(E*F);
    
        
        System.out.printf("VALOR A PAGAR: R$ %.2f\n",+G);
    }
 
}
